/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
  "./**/*.{js,jsx,ts,tsx}",
  "!./node_modules/**/*",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      // Mirror of src/constants/theme.ts. Keep the two in sync.
      colors: {
        surface: '#f8f9ff',
        'surface-dim': '#d2dbe9',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eef4ff',
        'surface-container': '#e5effd',
        'surface-container-high': '#e0e9f7',
        'surface-container-highest': '#dae3f1',
        'on-surface': '#131c26',
        'on-surface-variant': '#504534',
        'inverse-surface': '#28313c',
        'inverse-on-surface': '#e9f1ff',
        outline: '#827561',
        'outline-variant': '#d4c4ad',
        'surface-tint': '#7b5800',
        primary: '#7b5800',
        'on-primary': '#ffffff',
        'primary-container': '#f5b82e',
        'on-primary-container': '#684a00',
        'inverse-primary': '#fabc33',
        secondary: '#006c45',
        'on-secondary': '#ffffff',
        'secondary-container': '#86f9bc',
        'on-secondary-container': '#00734a',
        tertiary: '#815600',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#fdb436',
        'on-tertiary-container': '#6d4800',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffdea5',
        'primary-fixed-dim': '#fabc33',
        'on-primary-fixed': '#261900',
        'on-primary-fixed-variant': '#5d4200',
        'secondary-fixed': '#86f9bc',
        'secondary-fixed-dim': '#69dca1',
        'on-secondary-fixed': '#002112',
        'on-secondary-fixed-variant': '#005233',
        'tertiary-fixed': '#ffddb1',
        'tertiary-fixed-dim': '#ffba49',
        'on-tertiary-fixed': '#291800',
        'on-tertiary-fixed-variant': '#614000',
        background: '#f8f9ff',
        'on-background': '#131c26',
        'surface-variant': '#dae3f1',
        brand: {
          gold: '#FFF4D6',
          deepGold: '#D99512',
          border: '#E5E7EB',
          canvas: '#F8F9FA',
        },
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        xxl: '32px',
        huge: '48px',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      fontSize: {
        display: ['32px', { lineHeight: '40px', fontWeight: '700', letterSpacing: '-0.02em' }],
        h1: ['28px', { lineHeight: '34px', fontWeight: '700', letterSpacing: '-0.01em' }],
        'h1-mobile': ['24px', { lineHeight: '30px', fontWeight: '700', letterSpacing: '-0.01em' }],
        h2: ['24px', { lineHeight: '30px', fontWeight: '700' }],
        h3: ['20px', { lineHeight: '26px', fontWeight: '600' }],
        'body-lg': ['17px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '22px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500', letterSpacing: '0.02em' }],
      },
    },
  },
  plugins: [],
}